### ISSUE TITLE
`create-comit-app` start-env prints error on termination

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#141]
## Problem

When terminating the environment with `ctrl + C` it prints:
```
Error encountered when generating bitcoin blocks:
```

Command-line output: 
```
yarn create comit-app start-env
yarn create v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-comit-app@0.3.0" with binaries:
      - create-comit-app
[#################################] 33/33Creating Docker network (create-comit-app)...✓
Starting Ethereum node...✓
Starting Bitcoin node...✓
Writing configuration in env file...✓
Starting two cnds...✓
🎉 Environment is ready, time to create a COMIT app!
^CSignal received, terminating...
🧹 Cleaning up...
 dakami  ~  Error encountered when generating bitcoin blocks: Error(Hyper(Error(IncompleteMessage)), "http://localhost:54036/")
```

I encountered this every time I ran version `0.3.0`. 

## Goal

No error printing upon shutting down.

**Comment by bonomat** [comment]
Do you mind if we remove the `bug` label? For me this is more of a clean-up of the shutdown than a bug as it does not influence the behavior.

**Comment by D4nte** [comment]
Please note this is due to the fact that create-comit-app regularly sends a message to bitcoind to generate a new block.

When bitcoind is in the process of shutting done then it may not be able to process the `generate` command from create-comit-app and hence display the message.

This is not a bug but expected behaviour.

A solution to improve the situation would be to kill the generate future before killing bitcoind. Most likely by given a `receiver` end of a channel to the future and sending a message to tell it to stop when shutting done?
