### ISSUE TITLE
Improve COMIT workshop tooling and give back to the community

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#143]
Thanks to @thomaseizinger who kept discussing about this with me 😀

## Problem

One of the goals of our workshops is to prove that COMIT does what we say. In order to achieve this we interact with the respective blockchain clients to e.g. extract the HTLC from the block and show that it is actually the way we say. 
Unfortunately there is no tool (like e.g. a simple, local block explorer) that we can just reuse to to this. So we started to create "scripts" (first `curl`, then postman) to get the information from the blockchain clients we need. 
However, it is quite cumbersome to use this tools. On the other hand the tools HAVE to be low level enough, so one sees that the information is really directly from the blockchain client and not influenced by our software. 

## Goal

Make the experience of interacting with a blockchain client better (during our workshops). 

## Proposed solution

Create simple "blockchain explorers" that offer us exactly the functionality we need for the workshops, but can also be extended so that we can give back to the community. 

For the beginning those "blockchain explorers" should live inside create-comit-app and be driven by the examples. However, the architecture of those tools can be designed so it is extendable for other use-cases. 

### List of requirements for workshops
Overall it would be great if we tailer this to our needs so can show what we want to show with just a few clicks. 
The main question is: How far do we want to go and how extendable should it be for other use cases?

On an abstract level we need this for the workshops:
- Find certain transactions by ID (needed for e.g. showing the HTLC)
- Showing balances of specific addresses (needed to see how an example progresses, i.e. "now the HTLC holds the money, ..."

On a more concrete level this would result in:
- Link maker, taker accounts hardcoded
- Link the HTLCs there once it is available
- Show only the relevant transactions
- Include functionality to decode from HEX to DEC numbers
- Include functionality to decode bitcoin script
- Include functionality to decode ethereum contract

**Comment by bonomat** [comment]
Interesting idea.

Some thoughts: 

* > One of the goals of our workshops is to prove that COMIT does what we say.

I would express the goal of our workshops differently though. The goal is 
* to receive feedback on our tools, protocols, implementation, etc. and
* to teach others about how to use our tools and build on top of COMIT;

If it's about `proving that COMIT does what we say` we should probably go for a different approach. 

---- 

Nevertheless, I think you raise a valid point so I would describe the problem like this (please correct me if I misunderstood you)

## Problem: 
COMIT does a lot for the users _under the hood_ which is not directly visible to the users. Among others it takes care of constructing HTLCs, coming up with secrets, and generating deploy/fund/redeem/refund transactions.
This make it hard to understand what is happening when only using the provided examples, sdk. 

## Goal: 
Enable the user to follow the process of an atomic swap on chain.

## Recommendation

Create a _blockchain explorer_ which enables the user to follow what is happening during an atomic swap on the blockchain.
This may include: 
* Show account/address status: how much money does an address hold at any point of time
* Retrieve transaction details: deserialize if in hex into human readable format
* Show status of HTLCs

----

In regards of your other proposed features: 
* Include functionality to decode bitcoin script
* Include functionality to decode ethereum contract

I personally would not go that far. The reason is that even a human readable HTLC (see our RFCs for [ether](https://github.com/comit-network/RFCs/blob/master/RFC-007-SWAP-Basic-Ether.md#contract) or for [bitcoin](https://github.com/comit-network/RFCs/blob/master/RFC-005-SWAP-Basic-Bitcoin.adoc#contract)) is very hard to understand. 
I don't say we should not educate our developers, but I think doing so during a workshop where they just learned about how to use our tools will go beyond the scope of a simple `hands-on` workshop.

**Comment by da-kami** [comment]
Closed because:
* Needs more validation/goal and urgency.

Re-open if deemed necessary again.

Details:
* Unclear what goals we can validate with it.
* Too much work for achieving "educating people", use already existing tools (e.g. Postman is sufficient to make the point)
* A "nice to have" for very specific workshops (educating students) that we don't run that often.
* The argument of "creating a tool that gives us more visibility in the community" is currently not strong/urgent enough
