### ISSUE TITLE
CCA is downloaded multiple times

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#260]
## Problem

PR #258 makes you download `cca` multiple times if you run the examples.

This is due to the fact that:
- When doing `yarn create comit-app` it download the latest cca binary in the global yarn environment
- When doing `yarn start-env` in the project folder, it downloads the version specified by the `./package.json` in the local `node_modules` folder.

## Goal

To not download the same binary multiple times if the same version is used.
**Still** properly manage versions.

## Recommendation

Use a global user directory to store the create-comit-app binary.
One idea could be to use `~/.cache` (`$XDG_CACHE_DIR`).
Be sure to test this on mac, linux platform before rolling with it.

**Comment by D4nte** [comment]
Good thing I refactored everything before tackling the actual issue.

This is not a problem any more because the functionality is now split in 2 binaries:
- `yarn create comit-app` downloads the latest `create-comit-app` binary
- `yarn install` download the specific version of `comit-scripts` binary
